@startuml DIAGRAMMECLASS

  class Users {
  - id : int
  - lastName : string
  - firstName : string
  - email : string
  - telephone : string

  + getId() : int
  + getLastName() : string
  + getFirstName() : string
  + getEmail() : string
  + getTelephone() : string
}

class Reservations {
  - id : int
  - startDate : date
  - endDate : date
  - modificationDate : date
  - numberOfDays : int

  + getId() : int
  + getStartDate() : date
  + getEndDate() : date
  + getDateModification() : date
}
enum typeReservations {
  SHORTDURATION
  LONGDURATION
}

class Annonces {
  - id : int
  - publicationDate : date

  + getId( : int)
  + getPublicationDate() : date
}

class Logements {
  - id : int
  - postalCode : string
  - department : string
  - city : string
  - availability : boolean
  - numberOfRooms : int
  - floorNumber : int
  - rentPrice : float
  - balcony : boolean
  - garage : boolean
  - shower : boolean
  - elevator : boolean
  - nextToNeighbor : boolean
  - chargesIncluded : boolean
  
  + getId() : int
  + getFullAddress() : string
  + isAvailable() : boolean
  + getNumberOfRooms() : int
  + getFloorNumber() : int
  + getRentPrice() : float
  + getBalcony() : boolean
  + getElevator() : boolean
  + getNextToNeighbor() : boolean
  + getChargesIncluded() : boolean
  }

enum typeLogement {
  APARTMENT
  HOUSE
}

Tenants"0..*" -- "1..*"Reservations: réserve
Owners"1..*" -- "1..1"Annonces: possède
Annonces"0..*" -- "1..*"Reservations: appartient
Annonces"1..*" -- "0..*"Accommodations: appartient



    
@enduml